openapi: "3.1.0"
info:
  version: 1.0.0
  title: Outfit Of The Day
  description: Outfit Of The Day API Documentation
  termsOfService: http://swagger.io/terms/
  contact:
    name: Yoon
    email: baeyoojindev@gmail.com
servers:
  - url: https://ootd/api
tags:
  - name: User Profile Management
    description: Operations for user profiles
  - name: Weather Information
    description: Retrieve weather information
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: |
        {
          "error": $context.error.messageString
        }
paths:
  /weather:
    get:
      $ref: "./api_docs/resources/retrieve_weather.yml"
