version: '3'

tasks:
  init:
    desc: Initialize project
    cmds:
      - pip install pipenv
      - pipenv install --dev
      - pipenv shell

  bundle:
    desc: Bundle API documentation
    cmds:
      - npm install -g @redocly/cli
      - redocly bundle openapi.yml -o api_docs/api.yml --ext yaml

  api:
    desc: Create API documentation
    cmds:
      - echo "Building API documentation..."
      - npm install @redocly/cli -g
      - redocly build-docs api_docs/api.yml
      - echo "API documentation built successfully! Open HTML file in browser to view documentation."
