name: Store artifacts

runs:
  using: composite
  steps:
    - name: Upload
      shell: bash
      run: |
        sam package \
        --resolve-s3 \
        --s3-prefix "ootd-sam-bucket"

    - name: Artifact name
      id: artifact-name
      shell: bash
      run: |
        branch_name="${{ github.ref_name }}"
        github_branch_name=$(echo "$branch_name" | tr '/' '-')
        name="$github_branch_name-${{ github.run_number }}-${{ github.sha }}"
        echo "artifact-name=$name" >> "$GITHUB_OUTPUT"

    - name: Store aftifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifact-name.outputs.artifact-name }}
        path: |
          **/*
          !.aws-sam/build
          !.git
        retention-days: 7 
