name: Delete Dev-Feature
on:
  delete:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Set up sam
        uses: aws-actions/setup-sam@v2
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Sam delete
        run: |
          branch_name="$GITHUB_REF_NAME"
          github_branch_name=$(echo "$branch_name" | tr '/' '-')
          echo "$github_branch_name"
          sam delete --stack-name "$github_branch_name" --s3-bucket "ootd-sam-bucket" --no-prompts
