name: Dev Feature
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      
      - name: cfn-lint
        run: |
          pip3 install cfn-lint
          cfn-lint template.yml
      
  build:
    needs: test
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup
        uses: actions/setup

      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: '3.10'

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Set up sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate artifact
        run: make validate

      - name: Build artifact
        run: make build
      
      # - name: Sam build
      #   run: sam build --use-container

      - name: Store artifacts
        uses: 
        with:


      # - name: Sam deploy
      #   shell: bash
      #   run: |
      #     branch_name="$GITHUB_REF_NAME"
      #     github_branch_name=$(echo "$branch_name" | tr '/' '-')
      #     echo "$github_branch_name"
      #     sam deploy --stack-name "$github_branch_name" --no-fail-on-empty-changeset --parameter-overrides ResourceEnv="dev" ServiceEnv="$github_branch_name"
